### ISSUE TITLE
Vite rolldown 7.3 incompatibility

### ISSUE THREAD

**Issue by mkonecny** [mammadataei/cypress-vite#140]
Vite Rolldown ([vite rewritten in Rust](https://vite.dev/guide/rolldown)) 7.1 worked with this plugin, but 7.3 throws this error:

```

2026-01-30 03:44:32 UTC | Your configFile threw an error from: ../../apps/x/cypress.config.cjs
-- | --
2026-01-30 03:44:32 UTC |  
2026-01-30 03:44:32 UTC | We stopped running your tests because your config file crashed.
2026-01-30 03:44:32 UTC |  
2026-01-30 03:44:32 UTC | TypeError: manualChunks is not a function
2026-01-30 03:44:32 UTC | at name (file:///workdir/node_modules/rolldown/dist/shared/rolldown-build-BEU8N80I.mjs:2105:10)
2026-01-30 03:44:32 UTC | at name (file:///workdir/node_modules/rolldown/dist/shared/rolldown-build-BEU8N80I.mjs:2115:53)


```

Is it possible we either assign an empty function or `undefined` to `manualChunks` [here](https://github.com/mammadataei/cypress-vite/blob/630a5c7278ae90540d33c7e7b4c1e2bca090aa78/src/vitePreprocessor.ts#L85) line 85?

**Comment by MetRonnie** [comment]
May be fixed by #137?

**Comment by orianhexight** [comment]
PR #137 was merged and `cypress-vite` now works with Vite 8 at runtime. However, since Vite 8 is missing from the `peerDependencies` range, npm throws an ERESOLVE error on install. As a workaround, users need to add an override to their `package.json`:

```json
"overrides": {
  "cypress-vite": {
    "vite": "$vite"
  }
}
```

Would it be possible to add `^8.0.0` to the peer dependency range in the next release?

**Comment by bvandrc** [comment]
Fixed in [1.8.1](https://github.com/mammadataei/cypress-vite/pull/141) for Vite 7.

@orianhexight Vite 8 tests added, added as peer dep in [1.9.0](https://github.com/mammadataei/cypress-vite/pull/149)
