### ISSUE TITLE
TypeError: vitePreprocessor is not a function

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [mammadataei/cypress-vite#10]
Hi, i'm currently trying to get coverage working with `@cypress/code-coverage`, `vite-plugin-istanbul` and `cypress-vite`.

When i use in my `cypress.config.cjs` file:
```cjs
const vitePreprocessor = require('cypress-vite')
...
  e2e: {
    setupNodeEvents(on, config) {
      require('@cypress/code-coverage/task')(on, config)
      on('file:preprocessor', vitePreprocessor(path.resolve(__dirname, './vite.config.js')))
```
and run the unit tests for [our library](https://github.com/GIScience/openrouteservice-js/tree/feature/coverage) (repo type = module) with:
`VITE_COVERAGE=true start-server-and-test dev http://localhost:5173/ 'cypress run --e2e'`

i get the error:
`TypeError: vitePreprocessor is not a function`

<details>
  <summary>full error</summary>

```
Your configFile threw an error from: /Users/abutzer/Workspace/openrouteservice-js/cypress.config.cjs

The error was thrown while executing your e2e.setupNodeEvents() function:

TypeError: vitePreprocessor is not a function
    at setupNodeEvents (/Users/abutzer/Workspace/openrouteservice-js/cypress.config.cjs:19:31)
    at /Users/abutzer/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:118:14
    at tryCatcher (/Users/abutzer/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.attempt.Promise.try (/Users/abutzer/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at RunPlugins.load (/Users/abutzer/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:115:9)
    at RunPlugins.runSetupNodeEvents (/Users/abutzer/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:276:10)
    at EventEmitter.<anonymous> (/Users/abutzer/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:185:22)
    at EventEmitter.emit (node:events:513:28)
    at process.<anonymous> (/Users/abutzer/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: Command failed with exit code 1: cypress run --e2e
    at makeError (/Users/abutzer/Workspace/openrouteservice-js/node_modules/start-server-and-test/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/abutzer/Workspace/openrouteservice-js/node_modules/start-server-and-test/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 1: cypress run --e2e',
  command: 'cypress run --e2e',
  escapedCommand: '"cypress run --e2e"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
```
</details>

Is this a problem with the cypress-vite package? Or am i just not using it correctly?

Best regrads

**Comment by mammadataei** [comment]
Hi @TheGreatRefrigerator, thanks for reporting. The issue is related to the build process. I'll try to fix it. But for now, you can use this: 
```js
const vitePreprocessor = require('cypress-vite').default
```

**Comment by TheGreatRefrigerator** [comment]
@mammadataei thanks for the fast reaction.
It finds the function now.
I can still only generate coverage reports for the e2e and not unit-tests -.-. But that might not be an issue with cypress-vite

**Comment by mammadataei** [comment]
Patch released in [v1.2.1](https://github.com/mammadataei/cypress-vite/releases/tag/v1.2.1)

**Comment by thril** [comment]
FYI. After upgrading to 1.2.1, importing via ESM no longer works, but CJS does.

```
// does NOT work after upgrade
import vitePreprocessor from 'cypress-vite';

// does work
const vitePreprocessor = require('cypress-vite');
```

When using the ESM import, I get the following error:

```
TypeError: (0 , cypress_vite_1.default) is not a function
```

**Comment by TheGreatRefrigerator** [comment]
@thril what's your repository type? (or just link your repo)

i've run into this issue in the first place bc. i'm using vite's library bundling which needs a `type: module` in the package.json.

some context:
https://stackoverflow.com/questions/61401475/why-is-type-module-in-package-json-file
and
https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_enabling

**Comment by mammadataei** [comment]
@thril As discussed in #13, I think setting `"esModuleInterop": true,` in the `tsconfig.json` should fix the issue. Let me know in #13 if it doesn't work or you have any further problems.

**Comment by mammadataei** [comment]
@TheGreatRefrigerator, does the issue with cjs fixed in v1.2.1?

**Comment by TheGreatRefrigerator** [comment]
Yes, the current issue is fixed in v1.2.1 but i'm not using `cypress-vite` anymore, due to [issues](https://github.com/iFaxity/vite-plugin-istanbul/issues/28) in combination with `vite-plugin-istanbul` which doesn't respect my unit test coverage (don't really know how to debug this properly either).
So [i have to stay with the `babel-plugin-istanbul`](https://github.com/GIScience/openrouteservice-js/commit/170d35fb2630dcf228f4cd8ef2e6a1d77b0178b5#diff-27eb6ae753d0c50c354420406d0d3227ac6b42a22dd4b64367deac4b5fd4f2fe) which uses webpack to bundle for now.

**Comment by thril** [comment]
> @thril what's your repository type? (or just link your repo)
> 
> i've run into this issue in the first place bc. i'm using vite's library bundling which needs a `type: module` in the package.json.

@TheGreatRefrigerator It's a private repo, but does _not_ include `type: module`.

@mammadataei This was fixed with `"esModuleInterop": true`. Thanks.

I too am actually not using this package since I could never get it working. I kept getting an ENOENT error, which may have been due to the vite plugins I'm using or some other issue with my specific repo.
